Demo.PL/Controllers/DepartmentController.cs
using Demo.BLL.Interfaces;
using Demo.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        public IDepartmentRepository _departmentRepository { get; }

        public DepartmentController(IDepartmentRepository departmentRepository)
        {
            _departmentRepository = departmentRepository;
        }

        public IActionResult Index()
        {
            var departments = _departmentRepository.GetAll();
            return View(departments);
        }

        public IActionResult Create()
       {
            return View();
       }

        [HttpPost]
        public IActionResult Create(Department newDepartment)
        {
            if (ModelState.IsValid)
            {
               int Res = _departmentRepository.Add(newDepartment);
                if(Res > 0)
                {
                    TempData["Massage"] = "new Department is Created";
                }
                return RedirectToAction("Index");
            }
            return View(newDepartment);
        }

        public IActionResult Details(int ?id , string viewName = "Details")
        {
            if (id is null) return BadRequest();
            var department = _departmentRepository.GetById(id.Value);
            if (department is null) return NotFound();
            return View(viewName, department);
        }

        public IActionResult Edit(int ?id)
        {
            return Details(id , "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Department _Department , [FromRoute]int id)
        {
            if (_Department.Id != id) return BadRequest();
            if (ModelState.IsValid)
            {
                try {
                    _departmentRepository.Update(_Department);
                    return RedirectToAction("Index");
                }
                catch(System.Exception ex)
                {
                    ModelState.AddModelError(string.Empty , ex.Message);
                }

      
            }
            return View(_Department);   
        }

        public IActionResult Delete([FromRoute]int ? id)
        {
            if(id is null) return BadRequest();
            try
            {
                _departmentRepository.Delete(_departmentRepository.GetById(id.Value));
            }catch(System.Exception ex)
            {
                ModelState.AddModelError (string.Empty , ex.Message);
            }
            return RedirectToAction("Index");
        }
    }
}

Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Models;
using Demo.PL.Healper;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata;

namespace Demo.PL.Controllers
{
	[Authorize]
	public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IDepartmentRepository _departmentRepository;
        private readonly IMapper _mapper;

        public EmployeeController
            (IEmployeeRepository employeeRepository , IDepartmentRepository departmentRepository , IMapper mapper)
        {
            _employeeRepository = employeeRepository;
            _departmentRepository = departmentRepository;
            _mapper = mapper;
        }
        public IActionResult Index(string Name)
        {
            IEnumerable<EmployeeViewModel> MappedEmployees;
            IEnumerable<Employee>employees;
            if (string.IsNullOrEmpty(Name))
            {
                employees = _employeeRepository.GetAll();
            }else 
                employees = _employeeRepository.GetByName(Name);

            MappedEmployees = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);

            return View(MappedEmployees);
        }

      
        public IActionResult Add()
        {
            var Departments = _departmentRepository.GetAll();
            ViewBag.Departments = Departments;
            return View();
        }

        [HttpPost]
        public IActionResult Add(EmployeeViewModel employee)
        {
            if(ModelState.IsValid)
            {
                employee.ImageName = DocumentSettings.UplodeFile(employee.Image, "Images");
                Employee MappedEmployee = _mapper.Map<EmployeeViewModel , Employee>(employee);
                int Res = _employeeRepository.Add(MappedEmployee);
                if(Res > 0)
                {
                    TempData["Massage"] = "new Employee Added";
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        public IActionResult Details(int? id , string ViewName = "Details")
        {
            if (id is null) return BadRequest();
            var employee = _employeeRepository.GetById(id.Value);
            if (employee is null) return NotFound();

            var MappedEmployee = _mapper.Map<Employee , EmployeeViewModel>(employee);

            return View(ViewName, MappedEmployee);
        }

        public IActionResult Edit(int id)
        {
            var Departments = _departmentRepository.GetAll();
            ViewBag.Departments = Departments;
            return Details(id , "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EmployeeViewModel employee , [FromRoute] int id)
        {
            if (employee.Id != id) return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var MappedEmployee = _mapper.Map<EmployeeViewModel, Employee>(employee);
                    _employeeRepository.Update(MappedEmployee);
                    return RedirectToAction(nameof(Index));
                }
                catch(System.Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                }
            }
            return View(employee);
        }

        public IActionResult Delete(int id) {
            return Details(id, "Delete");
        }

        [HttpPost]
        public IActionResult Delete(EmployeeViewModel employee , [FromRoute] int id)
        {
            if(id != employee.Id) return BadRequest();
            try
            {
                var MappedEmployee = _mapper.Map<EmployeeViewModel, Employee>(employee);
                int effected = _employeeRepository.Delete(MappedEmployee);
                if(effected > 0 && employee.ImageName is not null)
                {
                    DocumentSettings.DeleteFile(employee.ImageName, "Images");
                }
                return RedirectToAction(nameof(Index));
            }catch(System.Exception e) {
                ModelState.AddModelError(string.Empty , e.Message);
            }
            return View(employee);
        }
    }
}

Demo.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link href="~/css/AuthStyleSheet.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<title>@ViewData["Title"]</title>
</head>
<body class="form-v4">
	<div class="page-content">
		<div class="form-v4-content">
			@RenderBody()
		</div>
	</div>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("ValidationSectionScripts", required: true)
</body>
</html>

Demo.PL/Views/Shared/_ButtonPartialView.cshtml
@model int 
<td><a asp-action="Details" asp-route-id="@Model"><i class="fa fa-eye"></i></a></td>
<td><a asp-action="Edit" asp-route-id="@Model"><i class="fa fa-edit"></i></a></td>
<td><a asp-action="Delete" asp-route-id="@Model"><i class="fa fa-trash"></i></a></td>

Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employess</a>
                        </li>
                        </li>
                        <li class="nav-item" style="margin-left : auto;">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["Massage"] is not null)
            {
                <div id="Alert" class="alert alert-success">
                    @TempData["Massage"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationSectionScripts", required: false)
    <script>
        $(document).ready(function () {
            // Show the div
            $("#Alert").show();

            // Set a timer to hide the div after 5 seconds (5000 milliseconds)
            setTimeout(function () {
                $("#Alert").fadeOut();
            }, 5000);
        });
    </script>
</body>
</html>